In [1]:
import requests

In [2]:
import pandas as pd
import numpy as np

In [3]:
import json

In [30]:
pd.options.mode.chained_assignment = None  # default='warn'

In [4]:
# Get all network information
x = requests.get('http://api.citybik.es/v2/networks')
x.status_code

200

In [33]:
networks = json.loads(x.content)

In [7]:
# Only need some of the fields 
n_limited = requests.get('http://api.citybik.es/v2/networks', params={'fields':'id,name'})
networks_limited_json = json.loads(n_limited.content)

networks_df = pd.DataFrame.from_dict(networks_limited_json.pop('networks'))
networks_df.head(10)

                      id                   name
0  abu-dhabi-careem-bike  Abu Dhabi Careem BIKE
1    acces-velo-saguenay             Accès Vélo
2                   aksu                   Aksu
3                   alba                   Alba
4               albabici               AlbaBici
5                 algira                 AlGira
6             almatybike             Almatybike
7     alsa-nextbike-leon     Alsa nextbike León
8             ambici-amb                 Ambici
9        ambici-badalona                 Ambici

In [8]:
# Pull Station data for DC's Bike Share, Capital Bikeshare
c = requests.get('http://api.citybik.es/v2/networks/capital-bikeshare', params={'fields':'stations'})
cabi = json.loads(c.content)
# cabi
cabi_stations = pd.DataFrame.from_dict(cabi.pop('network').pop('stations'))
cabi_stations.head(10)

,empty_slots,extra,free_bikes,id,latitude,longitude,name,timestamp
0,10,{'uid': '082623bf-1f3f-11e7-bf6b-3863bb334450'...,4,00082598b29c8a9211c1301ee0205a67,38.888097,-77.038325,17th St & Independence Ave SW,2025-07-21T14:24:27.234584+00:00Z
1,6,{'uid': '08253b95-1f3f-11e7-bf6b-3863bb334450'...,9,0034381c6fc2f698cfcd1f043db5302a,38.805630,-77.052925,Commerce St & Fayette St,2025-07-21T14:24:27.235004+00:00Z
2,14,{'uid': '066fd95e-0d37-4eea-a027-88c04277bb9d'...,0,003bcd1cd2030b68b53b8ed2b3415f5a,38.932243,-76.996133,7th & Monroe St NE,2025-07-21T14:24:27.234544+00:00Z
3,5,{'uid': '082569e6-1f3f-11e7-bf6b-3863bb334450'...,2,005ca183e4615210b71024bd6edae8fb,38.867217,-77.072296,Columbia Pike & S Orme St,2025-07-21T14:24:27.234603+00:00Z
4,31,{'uid': '08247e59-1f3f-11e7-bf6b-3863bb334450'...,1,0076a75098ef174de5673b2537b74fb1,38.930800,-77.031500,Park Rd & Holmead Pl NW,2025-07-21T14:24:27.264515+00:00Z
5,8,{'uid': '1e196ee1-daa4-4fa6-b6f8-197b31e6d170'...,7,007f114aec8fe690b5aae204f1f65b29,38.814031,-77.042817,N Pitt St & Montgomery St,2025-07-21T14:24:27.262540+00:00Z
6,9,{'uid': '0824e72a-1f3f-11e7-bf6b-3863bb334450'...,19,00abd2eca7c192efc1e11e145dc9724e,38.897857,-77.026975,11th & F St NW,2025-07-21T14:24:27.260993+00:00Z
7,2,"{'uid': '1939176485434179842', 'renting': 1, '...",12,00c176bfd1c5845d0b9a4cebff6fc6d6,38.975739,-77.066409,Western Ave & Pinehurst Cir NW,2025-07-21T14:24:27.237195+00:00Z
8,12,{'uid': 'b053927b-0761-40d0-a3ff-8a63fa1c7141'...,0,00d0198be9742b8e94eacfc9b4509032,39.051022,-77.115438,Rockville Pike & Rose Ave,2025-07-21T14:24:27.264388+00:00Z
9,18,{'uid': '343aa3f9-0b2f-4599-9854-81cbc04577f4'...,1,010527de7d3bfbcee48ae6dc122cb7dd,38.937849,-76.993509,10th & Quincy St NE / Turkey Thicket Rec,2025-07-21T14:24:27.245793+00:00Z

In [42]:
# stations with the most bikes
cabi_stations.sort_values('free_bikes', ascending=False).head(10)

,empty_slots,extra,free_bikes,id,latitude,longitude,name,timestamp
356,4,{'uid': '08249dad-1f3f-11e7-bf6b-3863bb334450'...,43,6e37eab19301e2a4f8723d01debd2fc9,38.893028,-77.026013,10th St & Constitution Ave NW,2025-06-05T17:21:30.718480+00:00Z
402,15,{'uid': '0824d0c6-1f3f-11e7-bf6b-3863bb334450'...,38,7a03f9cbe938f3be78aa94c699049942,38.896960,-77.004930,Columbus Circle / Union Station,2025-06-05T17:21:30.714411+00:00Z
69,3,{'uid': '0824c80d-1f3f-11e7-bf6b-3863bb334450'...,35,15084f7a937b270663b232cdc0fab47d,38.902061,-77.038322,17th & K St NW / Farragut Square,2025-06-05T17:21:30.813309+00:00Z
215,2,{'uid': '0824a623-1f3f-11e7-bf6b-3863bb334450'...,33,42549bd7d771a9c9a08f1293bdd15cd4,38.902801,-77.062819,Wisconsin Ave & K St NW,2025-06-05T17:21:30.723466+00:00Z
238,9,{'uid': '0824c69b-1f3f-11e7-bf6b-3863bb334450'...,32,497a312729b49320919ff090eb2b339f,38.894514,-77.031617,14th & D St NW / John A Wilson Building,2025-06-05T17:21:30.813655+00:00Z
585,14,{'uid': '08250371-1f3f-11e7-bf6b-3863bb334450'...,32,b65245dc2e0d3a25bde3b6e007f211b6,38.886372,-77.017701,4th & C St SW,2025-06-05T17:21:30.719758+00:00Z
646,9,{'uid': '0824c604-1f3f-11e7-bf6b-3863bb334450'...,29,cbeffc5e75006b56552643de4f5dcc58,38.898326,-77.027959,Metro Center / 12th & G St NW,2025-06-05T17:21:30.722024+00:00Z
660,6,{'uid': '0825fca2-1f3f-11e7-bf6b-3863bb334450'...,29,d0170a106f33e4b630acef3ec0df199a,38.898301,-77.039643,17th & G St NW,2025-06-05T17:21:30.718507+00:00Z
693,11,{'uid': '5f71434d-dc5c-45ff-8219-708a3d9a0691'...,28,dd6b05c0ca76d0c3a4dbe2fb0d0719f6,38.876893,-77.006072,1st & M St SE,2025-06-05T17:21:30.720602+00:00Z
140,18,{'uid': '08249b7f-1f3f-11e7-bf6b-3863bb334450'...,28,286411d9d0085a212c3ca18ddc8fab3b,38.886277,-77.028242,USDA / 12th & C St SW,2025-06-05T17:21:30.717490+00:00Z

In [10]:
# stations with the most parking spots
cabi_stations.sort_values('empty_slots', ascending=False).head(10)

,empty_slots,extra,free_bikes,id,latitude,longitude,name,timestamp
539,37,{'uid': '08247522-1f3f-11e7-bf6b-3863bb334450'...,0,a5d0ef943e552cc78205d5f8ad7f5731,38.929464,-77.027822,11th & Kenyon St NW,2025-07-21T14:24:27.261479+00:00Z
561,33,{'uid': '0824c309-1f3f-11e7-bf6b-3863bb334450'...,0,af76d115cb01553e9b728477c24e936a,38.894832,-76.987633,13th & D St NE,2025-07-21T14:24:27.263657+00:00Z
683,32,{'uid': '0824f8a2-1f3f-11e7-bf6b-3863bb334450'...,0,d97d47808baa37c6678746742ae60cd0,38.905900,-77.032500,Thomas Circle,2025-07-21T14:24:27.261788+00:00Z
4,31,{'uid': '08247e59-1f3f-11e7-bf6b-3863bb334450'...,1,0076a75098ef174de5673b2537b74fb1,38.930800,-77.031500,Park Rd & Holmead Pl NW,2025-07-21T14:24:27.264515+00:00Z
540,31,{'uid': '08256670-1f3f-11e7-bf6b-3863bb334450'...,0,a6ae4de96e611eb0ad99ce7412f3ba94,38.916787,-77.028139,12th & U St NW,2025-07-21T14:24:27.234834+00:00Z
427,30,{'uid': '0824749f-1f3f-11e7-bf6b-3863bb334450'...,0,81eaafc190c92a6d0990c59c6302b9c8,38.917764,-77.032096,14th & V St NW,2025-07-21T14:24:27.261385+00:00Z
403,30,{'uid': '0824d0c6-1f3f-11e7-bf6b-3863bb334450'...,23,7a03f9cbe938f3be78aa94c699049942,38.896960,-77.004930,Columbus Circle / Union Station,2025-07-21T14:24:27.234683+00:00Z
741,30,{'uid': '08247a21-1f3f-11e7-bf6b-3863bb334450'...,0,ed513ae29271c961898b99f592e3503f,38.908600,-77.032300,14th St & Rhode Island Ave NW,2025-07-21T14:24:27.243453+00:00Z
709,29,{'uid': '0824c229-1f3f-11e7-bf6b-3863bb334450'...,1,e26970d2053d48640b28b4e6ecb33f10,38.890461,-76.988355,Lincoln Park / 13th & East Capitol St NE,2025-07-21T14:24:27.234892+00:00Z
693,28,{'uid': '5f71434d-dc5c-45ff-8219-708a3d9a0691'...,9,dd6b05c0ca76d0c3a4dbe2fb0d0719f6,38.876893,-77.006072,1st & M St SE,2025-07-21T14:24:27.262282+00:00Z

In [18]:
# Capital coordinates -  38.889921, -77.011001
# Only want stations in northwest of the capital
nw_cabi_stations = cabi_stations[(cabi_stations['latitude'] > 38.889921) & (cabi_stations['longitude'] < -77.011001) ]
nw_cabi_stations['id'].count()

366

In [19]:
nw_cabi_stations.sort_values('free_bikes', ascending=False).head(10)

,empty_slots,extra,free_bikes,id,latitude,longitude,name,timestamp
238,6,{'uid': '0824c69b-1f3f-11e7-bf6b-3863bb334450'...,35,497a312729b49320919ff090eb2b339f,38.894514,-77.031617,14th & D St NW / John A Wilson Building,2025-07-21T14:24:27.264803+00:00Z
215,0,{'uid': '0824a623-1f3f-11e7-bf6b-3863bb334450'...,32,42549bd7d771a9c9a08f1293bdd15cd4,38.902801,-77.062819,Wisconsin Ave & K St NW,2025-07-21T14:24:27.264694+00:00Z
646,8,{'uid': '0824c604-1f3f-11e7-bf6b-3863bb334450'...,31,cbeffc5e75006b56552643de4f5dcc58,38.898326,-77.027959,Metro Center / 12th & G St NW,2025-07-21T14:24:27.261460+00:00Z
98,2,{'uid': '08254037-1f3f-11e7-bf6b-3863bb334450'...,30,1d3e16d324e455f4b1a17ba53ffd9a19,38.900880,-77.048911,22nd & I St NW / Foggy Bottom,2025-07-21T14:24:27.237111+00:00Z
660,4,{'uid': '0825fca2-1f3f-11e7-bf6b-3863bb334450'...,29,d0170a106f33e4b630acef3ec0df199a,38.898301,-77.039643,17th & G St NW,2025-07-21T14:24:27.260960+00:00Z
357,18,{'uid': '08249dad-1f3f-11e7-bf6b-3863bb334450'...,29,6e37eab19301e2a4f8723d01debd2fc9,38.893028,-77.026013,10th St & Constitution Ave NW,2025-07-21T14:24:27.261051+00:00Z
656,1,{'uid': '08249aa2-1f3f-11e7-bf6b-3863bb334450'...,28,cddfef5100fe74ef692df61569830a87,38.899632,-77.031686,14th St & New York Ave NW,2025-07-21T14:24:27.243712+00:00Z
437,1,{'uid': '0824a28b-1f3f-11e7-bf6b-3863bb334450'...,28,861b44f3d0763fa311a75d8acfa568e4,38.897222,-77.019347,5th & F St NW,2025-07-21T14:24:27.236290+00:00Z
69,13,{'uid': '0824c80d-1f3f-11e7-bf6b-3863bb334450'...,25,15084f7a937b270663b232cdc0fab47d,38.902061,-77.038322,17th & K St NW / Farragut Square,2025-07-21T14:24:27.265214+00:00Z
111,2,{'uid': 'b554d2fc-8912-4730-b2cb-9a3e1a96b223'...,24,213f13448b210e876b6a0f783dd0d1b2,38.901104,-77.028061,12th St & New York Ave NW,2025-07-21T14:24:27.236048+00:00Z

In [32]:
nw_cabi_stations['Total Slots'] = nw_cabi_stations['free_bikes'] + nw_cabi_stations['empty_slots']

nw_cabi_stations.loc[:,['name','Total Slots','free_bikes','empty_slots']].sort_values('Total Slots', ascending=False).head(10)

,name,Total Slots,free_bikes,empty_slots
357,10th St & Constitution Ave NW,47,29,18
514,21st & I St NW,45,21,24
238,14th & D St NW / John A Wilson Building,41,35,6
646,Metro Center / 12th & G St NW,39,31,8
69,17th & K St NW / Farragut Square,38,25,13
541,16th & K St NW/BLM Plaza,38,13,25
539,11th & Kenyon St NW,37,0,37
745,19th St & Constitution Ave NW,35,15,20
364,20th & O St NW / Dupont South,34,19,15
86,New Jersey Ave & F St NW,33,21,12